// Autogenerated using cbuild
System.config({
	map: {
		"@phosphor/algorithm": "node_modules/@phosphor/algorithm",
		"@phosphor/collections": "node_modules/@phosphor/collections",
		"@phosphor/commands": "node_modules/@phosphor/commands",
		"@phosphor/coreutils": "node_modules/@phosphor/coreutils",
		"@phosphor/disposable": "node_modules/@phosphor/disposable",
		"@phosphor/domutils": "node_modules/@phosphor/domutils",
		"@phosphor/dragdrop": "node_modules/@phosphor/dragdrop",
		"@phosphor/dragdrop/style/index.css": "node_modules/@phosphor/dragdrop/style/index.css",
		"@phosphor/keyboard": "node_modules/@phosphor/keyboard",
		"@phosphor/messaging": "node_modules/@phosphor/messaging",
		"@phosphor/properties": "node_modules/@phosphor/properties",
		"@phosphor/signaling": "node_modules/@phosphor/signaling",
		"@phosphor/virtualdom": "node_modules/@phosphor/virtualdom",
		"@phosphor/widgets": "node_modules/@phosphor/widgets",
		"@phosphor/widgets/style/index.css": "node_modules/@phosphor/widgets/style/index.css",
		"affine-hull": "node_modules/affine-hull",
		"babel-runtime/core-js/array/from": "node_modules/babel-runtime/core-js/array/from.js",
		"babel-runtime/core-js/object/assign": "node_modules/babel-runtime/core-js/object/assign.js",
		"babel-runtime/core-js/object/entries": "node_modules/babel-runtime/core-js/object/entries.js",
		"babel-runtime/core-js/object/values": "node_modules/babel-runtime/core-js/object/values.js",
		"babel-runtime/helpers/classCallCheck": "node_modules/babel-runtime/helpers/classCallCheck.js",
		"babel-runtime/helpers/extends": "node_modules/babel-runtime/helpers/extends.js",
		"babel-runtime/helpers/inherits": "node_modules/babel-runtime/helpers/inherits.js",
		"babel-runtime/helpers/objectWithoutProperties": "node_modules/babel-runtime/helpers/objectWithoutProperties.js",
		"babel-runtime/helpers/possibleConstructorReturn": "node_modules/babel-runtime/helpers/possibleConstructorReturn.js",
		"babel-runtime/helpers/typeof": "node_modules/babel-runtime/helpers/typeof.js",
		"base-64": "node_modules/base-64",
		"bit-twiddle": "node_modules/bit-twiddle",
		"charto-leaflet": "node_modules/charto-leaflet",
		"charto-model": "node_modules/charto-model",
		"classnames": "node_modules/classnames",
		"classy-mst": "node_modules/classy-mst",
		"convex-hull": "node_modules/convex-hull",
		"core-js/fn/object/assign": "node_modules/core-js/fn/object/assign.js",
		"core-js/library/fn/array/from": "node_modules/babel-runtime/node_modules/core-js/library/fn/array/from.js",
		"core-js/library/fn/object/assign": "node_modules/babel-runtime/node_modules/core-js/library/fn/object/assign.js",
		"core-js/library/fn/object/create": "node_modules/babel-runtime/node_modules/core-js/library/fn/object/create.js",
		"core-js/library/fn/object/entries": "node_modules/babel-runtime/node_modules/core-js/library/fn/object/entries.js",
		"core-js/library/fn/object/set-prototype-of": "node_modules/babel-runtime/node_modules/core-js/library/fn/object/set-prototype-of.js",
		"core-js/library/fn/object/values": "node_modules/babel-runtime/node_modules/core-js/library/fn/object/values.js",
		"core-js/library/fn/symbol": "node_modules/babel-runtime/node_modules/core-js/library/fn/symbol/index.js",
		"core-js/library/fn/symbol/iterator": "node_modules/babel-runtime/node_modules/core-js/library/fn/symbol/iterator.js",
		"dom-helpers/activeElement": "node_modules/dom-helpers/activeElement.js",
		"dom-helpers/class": "node_modules/dom-helpers/class/index.js",
		"dom-helpers/events": "node_modules/dom-helpers/events/index.js",
		"dom-helpers/events/off": "node_modules/dom-helpers/events/off.js",
		"dom-helpers/events/on": "node_modules/dom-helpers/events/on.js",
		"dom-helpers/ownerDocument": "node_modules/dom-helpers/ownerDocument.js",
		"dom-helpers/query/contains": "node_modules/dom-helpers/query/contains.js",
		"dom-helpers/query/isWindow": "node_modules/dom-helpers/query/isWindow.js",
		"dom-helpers/query/offset": "node_modules/dom-helpers/query/offset.js",
		"dom-helpers/query/position": "node_modules/dom-helpers/query/position.js",
		"dom-helpers/query/scrollTop": "node_modules/dom-helpers/query/scrollTop.js",
		"dom-helpers/style": "node_modules/dom-helpers/style/index.js",
		"dom-helpers/transition/properties": "node_modules/dom-helpers/transition/properties.js",
		"dom-helpers/util/inDOM": "node_modules/dom-helpers/util/inDOM.js",
		"dom-helpers/util/scrollbarSize": "node_modules/dom-helpers/util/scrollbarSize.js",
		"earcut": "node_modules/earcut",
		"events": "node_modules/events",
		"exenv": "node_modules/exenv",
		"fbjs/lib/EventListener": "node_modules/fbjs/lib/EventListener.js",
		"fbjs/lib/ExecutionEnvironment": "node_modules/fbjs/lib/ExecutionEnvironment.js",
		"fbjs/lib/camelizeStyleName": "node_modules/fbjs/lib/camelizeStyleName.js",
		"fbjs/lib/containsNode": "node_modules/fbjs/lib/containsNode.js",
		"fbjs/lib/emptyFunction": "node_modules/fbjs/lib/emptyFunction.js",
		"fbjs/lib/emptyObject": "node_modules/fbjs/lib/emptyObject.js",
		"fbjs/lib/focusNode": "node_modules/fbjs/lib/focusNode.js",
		"fbjs/lib/getActiveElement": "node_modules/fbjs/lib/getActiveElement.js",
		"fbjs/lib/hyphenateStyleName": "node_modules/fbjs/lib/hyphenateStyleName.js",
		"fbjs/lib/invariant": "node_modules/fbjs/lib/invariant.js",
		"fbjs/lib/shallowEqual": "node_modules/fbjs/lib/shallowEqual.js",
		"fbjs/lib/warning": "node_modules/fbjs/lib/warning.js",
		"geojson-area": "node_modules/geojson-area",
		"geojson-normalize": "node_modules/geojson-normalize",
		"geojson-random": "node_modules/geojson-random",
		"incremental-convex-hull": "node_modules/incremental-convex-hull",
		"invariant": "node_modules/invariant",
		"jsts": "node_modules/jsts",
		"keycode": "node_modules/keycode",
		"leaflet": "node_modules/leaflet",
		"leaflet-draw": "node_modules/leaflet-draw",
		"lodash/clone": "node_modules/lodash/clone.js",
		"lodash/forEach": "node_modules/lodash/forEach.js",
		"lodash/isEqual": "node_modules/lodash/isEqual.js",
		"lodash/isFunction": "node_modules/lodash/isFunction.js",
		"lodash/isUndefined": "node_modules/lodash/isUndefined.js",
		"lodash/keys": "node_modules/lodash/keys.js",
		"lodash/omit": "node_modules/lodash/omit.js",
		"lodash/pick": "node_modules/lodash/pick.js",
		"lodash/reduce": "node_modules/lodash/reduce.js",
		"lodash/uniqueId": "node_modules/lodash/uniqueId.js",
		"mobx": "node_modules/mobx",
		"mobx-react": "node_modules/mobx-react",
		"mobx-state-tree": "node_modules/mobx-state-tree",
		"moment": "node_modules/moment",
		"moment/locale/fi": "node_modules/moment/locale/fi.js",
		"monotone-convex-hull-2d": "node_modules/monotone-convex-hull-2d",
		"object-assign": "node_modules/object-assign",
		"phosphor-float-area": "node_modules/phosphor-float-area",
		"phosphor-float-area/style/index.css": "node_modules/phosphor-float-area/style/index.css",
		"popper.js": "node_modules/popper.js",
		"prop-types": "node_modules/prop-types",
		"prop-types-extra/lib/all": "node_modules/prop-types-extra/lib/all.js",
		"prop-types-extra/lib/componentOrElement": "node_modules/prop-types-extra/lib/componentOrElement.js",
		"prop-types-extra/lib/deprecated": "node_modules/prop-types-extra/lib/deprecated.js",
		"prop-types-extra/lib/elementType": "node_modules/prop-types-extra/lib/elementType.js",
		"prop-types-extra/lib/isRequiredForA11y": "node_modules/prop-types-extra/lib/isRequiredForA11y.js",
		"prop-types-extra/lib/utils/createChainableTypeChecker": "node_modules/prop-types-extra/lib/utils/createChainableTypeChecker.js",
		"prop-types/checkPropTypes": "node_modules/prop-types/checkPropTypes.js",
		"react": "node_modules/react",
		"react-bootstrap": "node_modules/react-bootstrap",
		"react-bootstrap-table": "node_modules/react-bootstrap-table",
		"react-bootstrap/lib/utils/bootstrapUtils": "node_modules/react-bootstrap/lib/utils/bootstrapUtils.js",
		"react-datepicker": "node_modules/react-datepicker",
		"react-dom": "node_modules/react-dom",
		"react-leaflet": "node_modules/react-leaflet",
		"react-modal": "node_modules/react-modal",
		"react-onclickoutside": "node_modules/react-onclickoutside",
		"react-overlays/lib/Modal": "node_modules/react-overlays/lib/Modal.js",
		"react-overlays/lib/Overlay": "node_modules/react-overlays/lib/Overlay.js",
		"react-overlays/lib/RootCloseWrapper": "node_modules/react-overlays/lib/RootCloseWrapper.js",
		"react-overlays/lib/Transition": "node_modules/react-overlays/lib/Transition.js",
		"react-overlays/lib/utils/isOverflowing": "node_modules/react-overlays/lib/utils/isOverflowing.js",
		"react-popper": "node_modules/react-popper",
		"react-s-alert": "node_modules/react-s-alert",
		"robust-orientation": "node_modules/robust-orientation",
		"robust-scale": "node_modules/robust-scale",
		"robust-subtract": "node_modules/robust-subtract",
		"robust-sum": "node_modules/robust-sum",
		"simplicial-complex": "node_modules/simplicial-complex",
		"simplify-js": "node_modules/simplify-js",
		"turf": "node_modules/turf",
		"turf-along": "node_modules/turf-along",
		"turf-area": "node_modules/turf-area",
		"turf-bbox": "node_modules/turf-bbox",
		"turf-bbox-polygon": "node_modules/turf-bbox-polygon",
		"turf-bearing": "node_modules/turf-bearing",
		"turf-bezier": "node_modules/turf-bezier",
		"turf-buffer": "node_modules/turf-buffer",
		"turf-center": "node_modules/turf-center",
		"turf-centroid": "node_modules/turf-centroid",
		"turf-collect": "node_modules/turf-collect",
		"turf-combine": "node_modules/turf-combine",
		"turf-concave": "node_modules/turf-concave",
		"turf-convex": "node_modules/turf-convex",
		"turf-destination": "node_modules/turf-destination",
		"turf-difference": "node_modules/turf-difference",
		"turf-distance": "node_modules/turf-distance",
		"turf-envelope": "node_modules/turf-envelope",
		"turf-explode": "node_modules/turf-explode",
		"turf-flip": "node_modules/turf-flip",
		"turf-grid": "node_modules/turf-grid",
		"turf-helpers": "node_modules/turf-helpers",
		"turf-hex-grid": "node_modules/turf-hex-grid",
		"turf-inside": "node_modules/turf-inside",
		"turf-intersect": "node_modules/turf-intersect",
		"turf-invariant": "node_modules/turf-invariant",
		"turf-isolines": "node_modules/turf-isolines",
		"turf-kinks": "node_modules/turf-kinks",
		"turf-line-distance": "node_modules/turf-line-distance",
		"turf-line-slice": "node_modules/turf-line-slice",
		"turf-meta": "node_modules/turf-meta",
		"turf-midpoint": "node_modules/turf-midpoint",
		"turf-nearest": "node_modules/turf-nearest",
		"turf-planepoint": "node_modules/turf-planepoint",
		"turf-point": "node_modules/turf-point",
		"turf-point-grid": "node_modules/turf-point-grid",
		"turf-point-on-line": "node_modules/turf-point-on-line",
		"turf-point-on-surface": "node_modules/turf-point-on-surface",
		"turf-random": "node_modules/turf-random",
		"turf-sample": "node_modules/turf-sample",
		"turf-simplify": "node_modules/turf-simplify",
		"turf-square": "node_modules/turf-square",
		"turf-square-grid": "node_modules/turf-square-grid",
		"turf-tag": "node_modules/turf-tag",
		"turf-tesselate": "node_modules/turf-tesselate",
		"turf-tin": "node_modules/turf-tin",
		"turf-triangle-grid": "node_modules/turf-triangle-grid",
		"turf-union": "node_modules/turf-union",
		"turf-within": "node_modules/turf-within",
		"two-product": "node_modules/two-product",
		"two-sum": "node_modules/two-sum",
		"uncontrollable": "node_modules/uncontrollable",
		"union-find": "node_modules/union-find",
		"validator": "node_modules/validator",
		"warning": "node_modules/warning",
		"wgs84": "node_modules/wgs84",
		"whatwg-fetch": "node_modules/whatwg-fetch"
	},
	meta: {
		"node_modules/*": { globals: { process: "bundler/node_modules/cbuild/process-dev.js" } }
	},
	packages: {
		"@phosphor/algorithm": {
			main: "lib/index.js"
		},
		"@phosphor/collections": {
			main: "lib/index.js"
		},
		"@phosphor/commands": {
			main: "lib/index.js"
		},
		"@phosphor/coreutils": {
			main: "lib/index.js"
		},
		"@phosphor/disposable": {
			main: "lib/index.js"
		},
		"@phosphor/domutils": {
			main: "lib/index.js"
		},
		"@phosphor/dragdrop": {
			main: "lib/index.js"
		},
		"@phosphor/keyboard": {
			main: "lib/index.js"
		},
		"@phosphor/messaging": {
			main: "lib/index.js"
		},
		"@phosphor/properties": {
			main: "lib/index.js"
		},
		"@phosphor/signaling": {
			main: "lib/index.js"
		},
		"@phosphor/virtualdom": {
			main: "lib/index.js"
		},
		"@phosphor/widgets": {
			main: "lib/index.js"
		},
		"affine-hull": {
			main: "aff.js"
		},
		"base-64": {
			main: "base64.js"
		},
		"bit-twiddle": {
			main: "twiddle.js"
		},
		"charto-leaflet": {
			main: "dist/index.js"
		},
		"charto-model": {
			main: "dist/index.js"
		},
		"classnames": {
			main: "index.js"
		},
		"classy-mst": {
			main: "dist/index.js"
		},
		"convex-hull": {
			main: "ch.js"
		},
		"earcut": {
			main: "src/earcut.js"
		},
		"events": {
			main: "events.js"
		},
		"exenv": {
			main: "index.js"
		},
		"geojson-area": {
			main: "index.js"
		},
		"geojson-normalize": {
			main: "index.js"
		},
		"geojson-random": {
			main: "index.js"
		},
		"incremental-convex-hull": {
			main: "ich.js"
		},
		"invariant": {
			main: "browser.js"
		},
		"jsts": {
			main: "dist/jsts.min.js"
		},
		"keycode": {
			main: "index.js"
		},
		"leaflet": {
			main: "dist/leaflet-src.js"
		},
		"leaflet-draw": {
			main: "dist/leaflet.draw.js"
		},
		"mobx": {
			main: "lib/mobx.js"
		},
		"mobx-react": {
			main: "index.js"
		},
		"mobx-state-tree": {
			main: "dist/mobx-state-tree.js"
		},
		"moment": {
			main: "moment.js"
		},
		"monotone-convex-hull-2d": {
			main: "index.js"
		},
		"node_modules/dom-helpers": {
			map: {
				"./style.js": "./style/index.js"
			}
		},
		"node_modules/react-bootstrap/lib": {
			map: {
				"./utils.js": "./utils/index.js"
			}
		},
		"object-assign": {
			main: "index.js"
		},
		"phosphor-float-area": {
			main: "dist/index.js"
		},
		"popper.js": {
			main: "dist/umd/popper.js"
		},
		"prop-types": {
			main: "index.js"
		},
		"react": {
			main: "index.js"
		},
		"react-bootstrap": {
			main: "lib/index.js"
		},
		"react-bootstrap-table": {
			main: "lib/index.js"
		},
		"react-datepicker": {
			main: "lib/index.js"
		},
		"react-dom": {
			main: "index.js"
		},
		"react-leaflet": {
			main: "lib/index.js",
			map: {
				"./lib/propTypes.js": "./lib/propTypes/index.js"
			}
		},
		"react-modal": {
			main: "lib/index.js"
		},
		"react-onclickoutside": {
			main: "lib/index.js"
		},
		"react-popper": {
			main: "lib/react-popper.js"
		},
		"react-s-alert": {
			main: "index.js"
		},
		"robust-orientation": {
			main: "orientation.js"
		},
		"robust-scale": {
			main: "robust-scale.js"
		},
		"robust-subtract": {
			main: "robust-diff.js"
		},
		"robust-sum": {
			main: "robust-sum.js"
		},
		"simplicial-complex": {
			main: "topology.js"
		},
		"simplify-js": {
			main: "simplify.js"
		},
		"turf": {
			main: "index.js"
		},
		"turf-along": {
			main: "index.js"
		},
		"turf-area": {
			main: "index.js"
		},
		"turf-bbox": {
			main: "index.js"
		},
		"turf-bbox-polygon": {
			main: "index.js"
		},
		"turf-bearing": {
			main: "index.js"
		},
		"turf-bezier": {
			main: "index.js"
		},
		"turf-buffer": {
			main: "index.js"
		},
		"turf-center": {
			main: "index.js"
		},
		"turf-centroid": {
			main: "index.js"
		},
		"turf-collect": {
			main: "index.js"
		},
		"turf-combine": {
			main: "index.js"
		},
		"turf-concave": {
			main: "index.js"
		},
		"turf-convex": {
			main: "index.js"
		},
		"turf-destination": {
			main: "index.js"
		},
		"turf-difference": {
			main: "index.js"
		},
		"turf-distance": {
			main: "index.js"
		},
		"turf-envelope": {
			main: "index.js"
		},
		"turf-explode": {
			main: "index.js"
		},
		"turf-flip": {
			main: "index.js"
		},
		"turf-grid": {
			main: "index.js"
		},
		"turf-helpers": {
			main: "index.js"
		},
		"turf-hex-grid": {
			main: "index.js"
		},
		"turf-inside": {
			main: "index.js"
		},
		"turf-intersect": {
			main: "index.js"
		},
		"turf-invariant": {
			main: "index.js"
		},
		"turf-isolines": {
			main: "index.js"
		},
		"turf-kinks": {
			main: "index.js"
		},
		"turf-line-distance": {
			main: "index.js"
		},
		"turf-line-slice": {
			main: "index.js"
		},
		"turf-meta": {
			main: "index.js"
		},
		"turf-midpoint": {
			main: "index.js"
		},
		"turf-nearest": {
			main: "index.js"
		},
		"turf-planepoint": {
			main: "index.js"
		},
		"turf-point": {
			main: "index.js"
		},
		"turf-point-grid": {
			main: "index.js"
		},
		"turf-point-on-line": {
			main: "index.js"
		},
		"turf-point-on-surface": {
			main: "index.js"
		},
		"turf-random": {
			main: "index.js"
		},
		"turf-sample": {
			main: "index.js"
		},
		"turf-simplify": {
			main: "index.js"
		},
		"turf-square": {
			main: "index.js"
		},
		"turf-square-grid": {
			main: "index.js"
		},
		"turf-tag": {
			main: "index.js"
		},
		"turf-tesselate": {
			main: "index.js"
		},
		"turf-tin": {
			main: "index.js"
		},
		"turf-triangle-grid": {
			main: "index.js"
		},
		"turf-union": {
			main: "index.js"
		},
		"turf-within": {
			main: "index.js"
		},
		"two-product": {
			main: "two-product.js"
		},
		"two-sum": {
			main: "two-sum.js"
		},
		"uncontrollable": {
			main: "index.js"
		},
		"union-find": {
			main: "index.js"
		},
		"validator": {
			main: "index.js"
		},
		"warning": {
			main: "browser.js"
		},
		"wgs84": {
			main: "index.js"
		},
		"whatwg-fetch": {
			main: "fetch.js"
		}
	}
});
