const initialState = {
  gid: undefined,
  class1_fi: undefined,
  class1_se: undefined,
  class1_en: undefined,
  class2_fi: undefined,
  class2_se: undefined,
  class2_en: undefined,
  name_fi: undefined,
  name_se: undefined,
  name_en: undefined,
  address: undefined,
  zip: undefined,
  municipali: undefined,
  munici_nro: undefined,
  subregion: undefined,
  subreg_nro: undefined,
  region: undefined,
  region_nro: undefined,
  info_fi: undefined,
  info_se: undefined,
  info_en: undefined,
  www_fi: undefined,
  www_se: undefined,
  www_en: undefined,
  chall_clas: undefined,
  length_m: undefined,
  accessibil: undefined,
  equipment: undefined,
  telephone: undefined,
  email: undefined,
  ownerclass: undefined,
  owner: undefined,
  upkeeper: undefined,
  upkeepinfo: undefined,
  upkeepclas: undefined,
  shapeestim: undefined,
  sh_es_date: undefined,
  timestamp: undefined,
  updater_id: undefined,
  x_eureffin: undefined,
  y_eureffin: undefined,
  special: undefined,
  no_address: undefined,
  publicinfo: undefined
}

export { initialState };
